import test from "node:test";
import assert from "node:assert/strict";
import { ContinuityAgent } from "../dist/core/modules/continuity-agent.js";

test("continuity agent blocks canonical persist when scene coverage and urgent open loops break", () => {
  const agent = new ContinuityAgent();
  const report = agent.audit({
    chapterNumber: 2,
    draft: {
      chapterNumber: 2,
      title: "矿坑后的夜里",
      content: "林凡被发去最脏的废道清理矿渣，但正文里没有承接上一章的断供威胁。",
      summary: "工作稿",
      basedOnPlan: 2,
    },
    plan: {
      targetChapterNumber: 2,
      chapterMission: "把赵执事的报复落到具体苦役上。",
      readerGoal: "承接上一章代价。",
      sceneBlueprint: [
        {
          sceneId: "scene-1",
          sceneAnchor: "scene-1-苦役",
          sceneNumber: 1,
          pov: "林凡",
          goal: "把打压变成具体苦役",
          conflict: "赵执事开始卡资源",
          turn: "林凡确认威胁正在落地",
          result: "林凡被迫接受危险苦役",
          newInformation: ["外门记录弟子也开始配合打压"],
          emotionalShift: "烦闷 -> 警惕",
          drivingCharacter: "赵执事",
          opposingForce: "林凡",
          decision: "先接下苦役",
          cost: "必须承担更危险任务",
          relationshipChange: "双方结怨升级",
          thematicTension: "反抗后代价升级",
          valuePositionA: "低头",
          valuePositionB: "硬抗",
          sceneStance: "压向更冷现实",
          styleDirective: "快节奏",
        },
        {
          sceneId: "scene-2",
          sceneAnchor: "scene-2-深井差事",
          sceneNumber: 2,
          pov: "林凡",
          goal: "把下章压力点钉在深井任务上",
          conflict: "新的差事牌逼他去深井",
          turn: "停发配给写成死规矩",
          result: "林凡没有退路",
          newInformation: ["深井任务会成为下一章直接威胁"],
          emotionalShift: "警惕 -> 决意",
          drivingCharacter: "赵执事",
          opposingForce: "林凡",
          decision: "接下差事牌",
          cost: "拒绝就停发三月配给",
          relationshipChange: "结怨转成制度性围剿",
          thematicTension: "代价持续升级",
          valuePositionA: "退让保命",
          valuePositionB: "硬扛到底",
          sceneStance: "把危险任务变成下章钩子",
          styleDirective: "收束留钩",
        },
      ],
      characterIntent: [],
      themeIntent: "推进反抗有代价",
      thematicQuestion: "反抗后代价如何持续升级",
      styleProfile: {
        narrationStyle: "直接",
        dialogueStyle: "克制",
        pacingProfile: "快",
        descriptionDensity: "低",
        toneConstraints: [],
      },
      gateNote: "",
    },
    analysis: {
      scenes: [
        {
          sceneId: "scene-1",
          sceneAnchor: "scene-1-苦役",
          sceneNumber: 1,
          pov: "林凡",
          goal: "把打压变成具体苦役",
          conflict: "赵执事开始卡资源",
          turn: "林凡确认威胁正在落地",
          result: "林凡被迫接受危险苦役",
          newInformation: ["外门记录弟子也开始配合打压"],
          emotionalShift: "烦闷 -> 警惕",
          sourceParagraphs: ["林凡被发去最脏的废道清理矿渣。"],
        },
      ],
      characterStates: [
        {
          name: "林凡",
          desire: "活下去并向上爬",
          fear: "被断供后失去修炼机会",
          misbelief: "再忍一忍就能熬过去",
          recentDecision: "先接下苦役",
          decisionCost: "要承担更危险的任务",
          relationshipShift: ["与赵执事的结怨升级"],
          arcProgress: "开始适应反抗后的连续代价",
          presentInChapter: true,
        },
      ],
      themeReport: {
        chapterNumber: 2,
        activeThemes: [],
      },
      styleReport: {
        averageSentenceLength: 16,
        dialogueRatio: 0.1,
        descriptionRatio: 0.25,
        rhythmNote: "",
        adherenceNote: "",
        styleDriftPoints: [],
        dialogueHomogeneitySpots: [],
        descriptionBalanceNote: "",
      },
      readerReport: {
        chapterNumber: 2,
        scores: {
          hook: 7,
          momentum: 7,
          emotionalPeak: 6,
          suspense: 7,
          memorability: 6,
        },
        summary: "代价开始压实。",
        strengths: [],
        risks: ["赵执事的断供威胁没有在本章具体落地。"],
        revisionSuggestions: [],
      },
      gateDecision: {
        chapterNumber: 2,
        gate: null,
        required: false,
        rationale: "",
      },
      revisionBrief: "",
    },
    settlement: {
      chapterSummary: {
        chapterNumber: 2,
        title: "矿坑后的夜里",
        summary: "林凡被迫接受危险苦役，但上一章最急迫的断供威胁没有被明确承接。",
        keyEvents: ["林凡被迫接受危险苦役"],
        changedCharacters: [],
        openedLoopIds: [],
        advancedLoopIds: [],
        closedLoopIds: [],
      },
      chapterStateDelta: {
        chapterNumber: 2,
        title: "矿坑后的夜里",
        changedCharacters: [],
        chronologyInsertions: [
          {
            eventId: "ch0002-scene-1",
            chapterNumber: 2,
            sceneNumber: 1,
            sceneId: "scene-1",
            actors: ["林凡", "赵执事"],
            summary: "林凡被发去最脏的废道清理矿渣",
            consequence: "他必须先接下危险苦役",
          },
        ],
        updatedLoops: [],
        stateHighlights: ["林凡被迫接受危险苦役"],
      },
      chronology: {
        events: [
          {
            eventId: "ch0002-scene-1",
            chapterNumber: 2,
            sceneNumber: 1,
            sceneId: "scene-1",
            actors: ["林凡", "赵执事"],
            summary: "林凡被发去最脏的废道清理矿渣",
            consequence: "他必须先接下危险苦役",
          },
        ],
      },
      openLoops: {
        loops: [],
      },
    },
    previousChronology: {
      events: [
        {
          eventId: "ch0001-scene-3",
          chapterNumber: 1,
          sceneNumber: 3,
          sceneId: "scene-3",
          actors: ["林凡", "赵执事"],
          summary: "林凡当众夺回灵石",
          consequence: "赵执事决定后续断供并加重打压",
        },
      ],
    },
    previousOpenLoops: {
      loops: [
        {
          loopId: "loop-ch0001-01",
          type: "threat",
          introducedInChapter: 1,
          owner: "赵执事",
          description: "后续资源可能被彻底断供，甚至被安排危险差事",
          expectedPayoffWindow: "soon",
          urgency: "high",
          status: "open",
          payoffConstraints: ["下一章必须承接断供或危险差事"],
          relatedEntities: ["赵执事", "林凡"],
          evidenceRefs: ["scene-4"],
          lastUpdatedChapter: 1,
        },
      ],
    },
    previousCharacterHistory: [
      {
        name: "林凡",
        latestState: {
          name: "林凡",
          desire: "改变命运",
          fear: "被断供后失去修炼机会",
          misbelief: "再忍一忍就能熬过去",
          recentDecision: "当众夺回灵石",
          decisionCost: "赵执事准备断供并加重打压",
          relationshipShift: ["与赵执事公开对立"],
          arcProgress: "第一次公开反抗规则",
          presentInChapter: true,
        },
        timeline: [],
      },
    ],
    worldRules: {
      rules: [],
    },
  });

  assert.equal(report.blocking, true);
  assert.ok(report.issues.some((issue) => issue.code === "scene_coverage_conflict"));
  assert.ok(report.issues.some((issue) => issue.code === "open_loop_conflict"));
});

test("continuity agent allows canonical persist when scene coverage and urgent loops are carried forward", () => {
  const agent = new ContinuityAgent();
  const report = agent.audit({
    chapterNumber: 2,
    draft: {
      chapterNumber: 2,
      title: "矿坑后的夜里",
      content: "赵执事真的断了林凡的配给，还把他赶去西三区深井。林凡知道这口井就是下一轮打压的起点。",
      summary: "工作稿",
      basedOnPlan: 2,
    },
    plan: {
      targetChapterNumber: 2,
      chapterMission: "把断供与深井任务压实。",
      readerGoal: "承接上一章代价。",
      sceneBlueprint: [
        {
          sceneId: "scene-1",
          sceneAnchor: "scene-1-苦役",
          sceneNumber: 1,
          pov: "林凡",
          goal: "把断供落地",
          conflict: "赵执事真的开始断供",
          turn: "林凡意识到断供是制度性打压",
          result: "深井任务变成下一章直接威胁",
          newInformation: ["西三区深井会成为下一章主压力"],
          emotionalShift: "烦闷 -> 警惕",
          drivingCharacter: "赵执事",
          opposingForce: "林凡",
          decision: "先吞下这口气",
          cost: "接下危险任务",
          relationshipChange: "双方结怨升级",
          thematicTension: "反抗后代价升级",
          valuePositionA: "低头",
          valuePositionB: "硬抗",
          sceneStance: "现实更冷",
          styleDirective: "快节奏",
        },
      ],
      characterIntent: [],
      themeIntent: "推进反抗有代价",
      thematicQuestion: "反抗后代价如何持续升级",
      styleProfile: {
        narrationStyle: "直接",
        dialogueStyle: "克制",
        pacingProfile: "快",
        descriptionDensity: "低",
        toneConstraints: [],
      },
      gateNote: "",
    },
    analysis: {
      scenes: [
        {
          sceneId: "scene-1",
          sceneAnchor: "scene-1-苦役",
          sceneNumber: 1,
          pov: "林凡",
          goal: "把断供落地",
          conflict: "赵执事真的开始断供",
          turn: "林凡意识到断供是制度性打压",
          result: "深井任务变成下一章直接威胁",
          newInformation: ["西三区深井会成为下一章主压力"],
          emotionalShift: "烦闷 -> 警惕",
          sourceParagraphs: ["赵执事真的断了林凡的配给，还把他赶去西三区深井。"],
        },
      ],
      characterStates: [
        {
          name: "林凡",
          desire: "活下去并向上爬",
          fear: "被断供后失去修炼机会",
          misbelief: "再忍一忍就能熬过去",
          recentDecision: "先接下深井任务",
          decisionCost: "必须去更危险的深井",
          relationshipShift: ["与赵执事的结怨升级"],
          arcProgress: "反抗后的代价开始持续升级",
          presentInChapter: true,
        },
      ],
      themeReport: {
        chapterNumber: 2,
        activeThemes: [],
      },
      styleReport: {
        averageSentenceLength: 16,
        dialogueRatio: 0.1,
        descriptionRatio: 0.25,
        rhythmNote: "",
        adherenceNote: "",
        styleDriftPoints: [],
        dialogueHomogeneitySpots: [],
        descriptionBalanceNote: "",
      },
      readerReport: {
        chapterNumber: 2,
        scores: {
          hook: 7,
          momentum: 8,
          emotionalPeak: 6,
          suspense: 7,
          memorability: 6,
        },
        summary: "断供和深井威胁已经承接到位。",
        strengths: [],
        risks: [],
        revisionSuggestions: [],
      },
      gateDecision: {
        chapterNumber: 2,
        gate: null,
        required: false,
        rationale: "",
      },
      revisionBrief: "",
    },
    settlement: {
      chapterSummary: {
        chapterNumber: 2,
        title: "矿坑后的夜里",
        summary: "赵执事真的断了林凡的配给，还把他赶去西三区深井。",
        keyEvents: ["赵执事断供并安排深井任务"],
        changedCharacters: [],
        openedLoopIds: ["loop-ch0002-01"],
        advancedLoopIds: ["loop-ch0001-01"],
        closedLoopIds: [],
      },
      chapterStateDelta: {
        chapterNumber: 2,
        title: "矿坑后的夜里",
        changedCharacters: [],
        chronologyInsertions: [
          {
            eventId: "ch0002-scene-1",
            chapterNumber: 2,
            sceneNumber: 1,
            sceneId: "scene-1",
            actors: ["林凡", "赵执事"],
            summary: "赵执事真的断了林凡的配给",
            consequence: "林凡被赶去西三区深井",
          },
        ],
        updatedLoops: [
          {
            loopId: "loop-ch0001-01",
            action: "advanced",
            description: "后续资源可能被彻底断供，甚至被安排危险差事",
            evidence: "scene-1",
          },
        ],
        stateHighlights: ["断供与深井威胁落地"],
      },
      chronology: {
        events: [
          {
            eventId: "ch0002-scene-1",
            chapterNumber: 2,
            sceneNumber: 1,
            sceneId: "scene-1",
            actors: ["林凡", "赵执事"],
            summary: "赵执事真的断了林凡的配给",
            consequence: "林凡被赶去西三区深井",
          },
        ],
      },
      openLoops: {
        loops: [
          {
            loopId: "loop-ch0001-01",
            type: "threat",
            introducedInChapter: 1,
            owner: "赵执事",
            description: "后续资源可能被彻底断供，甚至被安排危险差事",
            expectedPayoffWindow: "soon",
            urgency: "high",
            status: "advanced",
            payoffConstraints: ["下一章必须承接断供或危险差事"],
            relatedEntities: ["赵执事", "林凡"],
            evidenceRefs: ["scene-1"],
            lastUpdatedChapter: 2,
          },
        ],
      },
    },
    previousChronology: {
      events: [
        {
          eventId: "ch0001-scene-3",
          chapterNumber: 1,
          sceneNumber: 3,
          sceneId: "scene-3",
          actors: ["林凡", "赵执事"],
          summary: "林凡当众夺回灵石",
          consequence: "赵执事决定后续断供并加重打压",
        },
      ],
    },
    previousOpenLoops: {
      loops: [
        {
          loopId: "loop-ch0001-01",
          type: "threat",
          introducedInChapter: 1,
          owner: "赵执事",
          description: "后续资源可能被彻底断供，甚至被安排危险差事",
          expectedPayoffWindow: "soon",
          urgency: "high",
          status: "open",
          payoffConstraints: ["下一章必须承接断供或危险差事"],
          relatedEntities: ["赵执事", "林凡"],
          evidenceRefs: ["scene-4"],
          lastUpdatedChapter: 1,
        },
      ],
    },
    previousCharacterHistory: [
      {
        name: "林凡",
        latestState: {
          name: "林凡",
          desire: "改变命运",
          fear: "被断供后失去修炼机会",
          misbelief: "再忍一忍就能熬过去",
          recentDecision: "当众夺回灵石",
          decisionCost: "赵执事准备断供并加重打压",
          relationshipShift: ["与赵执事公开对立"],
          arcProgress: "第一次公开反抗规则",
          presentInChapter: true,
        },
        timeline: [],
      },
    ],
    worldRules: {
      rules: [],
    },
  });

  assert.equal(report.blocking, false);
  assert.equal(report.issues.length, 0);
});

test("continuity agent blocks canonical persist when world rules are violated", () => {
  const agent = new ContinuityAgent();
  const report = agent.audit({
    chapterNumber: 2,
    draft: {
      chapterNumber: 2,
      title: "深井口的火光",
      content: "林凡摸出一把手枪，顶住陈师兄的眉心。赵执事刚想喝止，林凡已经扣下扳机。",
      summary: "工作稿",
      basedOnPlan: 2,
    },
    plan: {
      targetChapterNumber: 2,
      chapterMission: "把上章代价推进成更硬的压迫。",
      readerGoal: "承接反抗后的后果。",
      sceneBlueprint: [
        {
          sceneId: "scene-1",
          sceneAnchor: "scene-1-深井口",
          sceneNumber: 1,
          pov: "林凡",
          goal: "把代价压到深井任务上",
          conflict: "赵执事把危险差事压到林凡头上",
          turn: "林凡发现深井口有人故意堵他",
          result: "冲突升级为更公开的对抗",
          newInformation: ["西三区深井已经被人提前做了手脚"],
          emotionalShift: "警惕 -> 绷紧",
          drivingCharacter: "林凡",
          opposingForce: "赵执事",
          decision: "硬接深井任务",
          cost: "危险差事直接压到身上",
          relationshipChange: "与赵执事公开撕破脸",
          thematicTension: "反抗后的代价变得更具体",
          valuePositionA: "低头保命",
          valuePositionB: "硬扛到底",
          sceneStance: "继续压向更冷现实",
          styleDirective: "快节奏",
        },
      ],
      characterIntent: [],
      themeIntent: "反抗有代价",
      thematicQuestion: "主角还能否承受反抗后的持续打压",
      styleProfile: {
        narrationStyle: "直接",
        dialogueStyle: "克制",
        pacingProfile: "快",
        descriptionDensity: "低",
        toneConstraints: [],
      },
      gateNote: "",
    },
    analysis: {
      scenes: [
        {
          sceneId: "scene-1",
          sceneAnchor: "scene-1-深井口",
          sceneNumber: 1,
          pov: "林凡",
          goal: "把代价压到深井任务上",
          conflict: "赵执事把危险差事压到林凡头上",
          turn: "林凡发现深井口有人故意堵他",
          result: "冲突升级为更公开的对抗",
          newInformation: ["西三区深井已经被人提前做了手脚"],
          emotionalShift: "警惕 -> 绷紧",
          sourceParagraphs: ["林凡摸出一把手枪，顶住陈师兄的眉心。"],
        },
      ],
      characterStates: [
        {
          name: "林凡",
          desire: "活下去并向上爬",
          fear: "被彻底断供后再无翻身机会",
          misbelief: "只要够狠就能立刻吓住所有人",
          recentDecision: "在深井口直接亮出手枪",
          decisionCost: "会把冲突推到不可收拾的地步",
          relationshipShift: ["与赵执事彻底公开对立"],
          arcProgress: "开始误把极端手段当成唯一出路",
          presentInChapter: true,
        },
      ],
      themeReport: {
        chapterNumber: 2,
        activeThemes: [],
      },
      styleReport: {
        averageSentenceLength: 15,
        dialogueRatio: 0.1,
        descriptionRatio: 0.2,
        rhythmNote: "",
        adherenceNote: "",
        styleDriftPoints: [],
        dialogueHomogeneitySpots: [],
        descriptionBalanceNote: "",
      },
      readerReport: {
        chapterNumber: 2,
        scores: {
          hook: 7,
          momentum: 8,
          emotionalPeak: 7,
          suspense: 6,
          memorability: 6,
        },
        summary: "冲突升级，但世界规则明显跑偏。",
        strengths: [],
        risks: ["现代热武器和当前修仙设定明显冲突。"],
        revisionSuggestions: ["把现代枪械替换成符合世界规则的差事牌、法器或矿井机关。"],
      },
      gateDecision: {
        chapterNumber: 2,
        gate: null,
        required: false,
        rationale: "",
      },
      revisionBrief: "",
    },
    settlement: {
      chapterSummary: {
        chapterNumber: 2,
        title: "深井口的火光",
        summary: "林凡在深井口亮出了不属于这个世界观的现代枪械。",
        keyEvents: ["林凡亮出手枪威胁陈师兄"],
        changedCharacters: [],
        openedLoopIds: [],
        advancedLoopIds: [],
        closedLoopIds: [],
      },
      chapterStateDelta: {
        chapterNumber: 2,
        title: "深井口的火光",
        changedCharacters: [],
        chronologyInsertions: [
          {
            eventId: "ch0002-scene-1",
            chapterNumber: 2,
            sceneNumber: 1,
            sceneId: "scene-1",
            actors: ["林凡", "陈师兄", "赵执事"],
            summary: "林凡在深井口亮出手枪威胁陈师兄",
            consequence: "冲突被推进到不符合设定的热武器对峙",
          },
        ],
        updatedLoops: [],
        stateHighlights: ["现代热武器闯入修仙场景"],
      },
      chronology: {
        events: [
          {
            eventId: "ch0002-scene-1",
            chapterNumber: 2,
            sceneNumber: 1,
            sceneId: "scene-1",
            actors: ["林凡", "陈师兄", "赵执事"],
            summary: "林凡在深井口亮出手枪威胁陈师兄",
            consequence: "冲突被推进到不符合设定的热武器对峙",
          },
        ],
      },
      openLoops: {
        loops: [],
      },
    },
    previousChronology: {
      events: [],
    },
    previousOpenLoops: {
      loops: [],
    },
    previousCharacterHistory: [],
    worldRules: {
      rules: [
        {
          ruleId: "no-modern-firearms",
          description: "本书修仙主线里禁止现代热武器直接入场。",
          severity: "high",
          forbiddenPhrases: ["手枪", "步枪", "冲锋枪"],
          appliesWhenAnyPhrases: [],
          requiredPhrases: [],
        },
      ],
    },
  });

  assert.equal(report.blocking, true);
  assert.ok(report.issues.some((issue) => issue.code === "world_rule_conflict"));
  assert.equal(report.checkedCounts.worldRules, 1);
  assert.equal(report.skippedChecks.length, 0);
});

test("continuity agent flags reveal conflicts when a mystery appears revealed but settlement does not advance the loop", () => {
  const agent = new ContinuityAgent();
  const report = agent.audit({
    chapterNumber: 3,
    draft: {
      chapterNumber: 3,
      title: "门铃声后的名字",
      content: "林凡终于明白，母亲失踪那夜的门铃声不是巧合。真相已经快要被说破，可本章账本没有登记这条旧谜题的推进。",
      summary: "工作稿",
      basedOnPlan: 3,
    },
    plan: {
      targetChapterNumber: 3,
      chapterMission: "把母亲失踪之谜往前推一步。",
      readerGoal: "承接旧谜题并留下更深一层疑问。",
      sceneBlueprint: [
        {
          sceneId: "scene-1",
          sceneAnchor: "scene-1-门铃",
          sceneNumber: 1,
          pov: "林凡",
          goal: "触碰母亲失踪之谜",
          conflict: "记忆与现实对不上",
          turn: "林凡从门铃声里听出新的含义",
          result: "谜题看似被推进",
          newInformation: ["门铃声和失踪夜存在更直接联系"],
          emotionalShift: "困惑 -> 发冷",
          drivingCharacter: "林凡",
          opposingForce: "旧记忆",
          decision: "继续追查门铃声",
          cost: "更靠近母亲失踪真相",
          relationshipChange: "与母亲留下的线索关系变得更直接",
          thematicTension: "越接近真相越难回头",
          valuePositionA: "停下自保",
          valuePositionB: "继续追查",
          sceneStance: "继续压向真相",
          styleDirective: "压低说明，保留悬念",
        },
      ],
      characterIntent: [],
      themeIntent: "真相的代价",
      thematicQuestion: "追查真相是否值得付出代价",
      styleProfile: {
        narrationStyle: "直接",
        dialogueStyle: "克制",
        pacingProfile: "快",
        descriptionDensity: "低",
        toneConstraints: [],
      },
      gateNote: "",
    },
    analysis: {
      scenes: [
        {
          sceneId: "scene-1",
          sceneAnchor: "scene-1-门铃",
          sceneNumber: 1,
          pov: "林凡",
          goal: "触碰母亲失踪之谜",
          conflict: "记忆与现实对不上",
          turn: "林凡从门铃声里听出新的含义",
          result: "谜题看似被推进",
          newInformation: ["门铃声和失踪夜存在更直接联系"],
          emotionalShift: "困惑 -> 发冷",
          sourceParagraphs: ["林凡终于明白，母亲失踪那夜的门铃声不是巧合。"],
        },
      ],
      characterStates: [
        {
          name: "林凡",
          desire: "找出母亲失踪真相",
          fear: "真相会证明母亲不是失踪而是被人故意带走",
          misbelief: "只要追得够快就能撑住代价",
          recentDecision: "继续追查门铃声",
          decisionCost: "会更深卷进旧案",
          relationshipShift: ["与母亲留下的线索重新绑定"],
          arcProgress: "开始主动逼近真相线",
          presentInChapter: true,
        },
      ],
      themeReport: {
        chapterNumber: 3,
        activeThemes: [],
      },
      styleReport: {
        averageSentenceLength: 14,
        dialogueRatio: 0.1,
        descriptionRatio: 0.2,
        rhythmNote: "",
        adherenceNote: "",
        styleDriftPoints: [],
        dialogueHomogeneitySpots: [],
        descriptionBalanceNote: "",
      },
      readerReport: {
        chapterNumber: 3,
        scores: {
          hook: 8,
          momentum: 7,
          emotionalPeak: 7,
          suspense: 8,
          memorability: 7,
        },
        summary: "旧谜题被碰到了，但账本没有同步推进。",
        strengths: [],
        risks: ["章节已经有揭示口吻，但 loop 状态没动。"],
        revisionSuggestions: [],
      },
      gateDecision: {
        chapterNumber: 3,
        gate: null,
        required: false,
        rationale: "",
      },
      revisionBrief: "",
    },
    settlement: {
      chapterSummary: {
        chapterNumber: 3,
        title: "门铃声后的名字",
        summary: "林凡似乎摸到了母亲失踪之谜的边缘。",
        keyEvents: ["林凡重新理解门铃声"],
        changedCharacters: [],
        openedLoopIds: [],
        advancedLoopIds: [],
        closedLoopIds: [],
      },
      chapterStateDelta: {
        chapterNumber: 3,
        title: "门铃声后的名字",
        changedCharacters: [],
        chronologyInsertions: [
          {
            eventId: "ch0003-scene-1",
            chapterNumber: 3,
            sceneNumber: 1,
            sceneId: "scene-1",
            actors: ["林凡"],
            summary: "林凡重新理解母亲失踪夜的门铃声",
            consequence: "真相似乎快要被说破",
          },
        ],
        updatedLoops: [],
        stateHighlights: ["旧谜题被再次碰触"],
      },
      chronology: {
        events: [
          {
            eventId: "ch0003-scene-1",
            chapterNumber: 3,
            sceneNumber: 1,
            sceneId: "scene-1",
            actors: ["林凡"],
            summary: "林凡重新理解母亲失踪夜的门铃声",
            consequence: "真相似乎快要被说破",
          },
        ],
      },
      openLoops: {
        loops: [],
      },
    },
    previousChronology: {
      events: [],
    },
    previousOpenLoops: {
      loops: [
        {
          loopId: "loop-ch0001-02",
          type: "mystery",
          introducedInChapter: 1,
          owner: "林凡",
          description: "母亲失踪那夜的门铃声到底意味着什么",
          expectedPayoffWindow: "soon",
          urgency: "high",
          status: "open",
          payoffConstraints: ["近几章必须持续推进谜题"],
          relatedEntities: ["林凡", "母亲", "门铃声"],
          evidenceRefs: ["scene-4"],
          lastUpdatedChapter: 1,
        },
      ],
    },
    previousCharacterHistory: [],
    worldRules: {
      rules: [],
    },
  });

  assert.equal(report.blocking, true);
  assert.ok(report.issues.some((issue) => issue.code === "reveal_conflict"));
});

test("continuity agent flags abrupt character state drift without transition support", () => {
  const agent = new ContinuityAgent();
  const report = agent.audit({
    chapterNumber: 4,
    draft: {
      chapterNumber: 4,
      title: "冷井口",
      content: "林凡忽然只想安稳活下去，也不再相信追查任何真相值得付代价，但正文里没有写出这种转变是怎么发生的。",
      summary: "工作稿",
      basedOnPlan: 4,
    },
    plan: {
      targetChapterNumber: 4,
      chapterMission: "把深井压力继续压实。",
      readerGoal: "承接深井任务后的连续代价。",
      sceneBlueprint: [
        {
          sceneId: "scene-1",
          sceneAnchor: "scene-1-井口",
          sceneNumber: 1,
          pov: "林凡",
          goal: "继续承受深井压力",
          conflict: "危险任务逼近",
          turn: "林凡开始想躲开这条线",
          result: "人物状态看起来突然反向转折",
          newInformation: ["深井下方可能埋着更大的秘密"],
          emotionalShift: "绷紧 -> 退缩",
          drivingCharacter: "林凡",
          opposingForce: "深井任务",
          decision: "先避开深井",
          cost: "会错过继续追查旧线的机会",
          relationshipChange: "与旧线保持距离",
          thematicTension: "求生与追查真相的冲突",
          valuePositionA: "保命退让",
          valuePositionB: "继续追查",
          sceneStance: "压向退缩",
          styleDirective: "克制",
        },
      ],
      characterIntent: [],
      themeIntent: "代价让人退缩",
      thematicQuestion: "人是否会被连续代价彻底压回去",
      styleProfile: {
        narrationStyle: "直接",
        dialogueStyle: "克制",
        pacingProfile: "快",
        descriptionDensity: "低",
        toneConstraints: [],
      },
      gateNote: "",
    },
    analysis: {
      scenes: [
        {
          sceneId: "scene-1",
          sceneAnchor: "scene-1-井口",
          sceneNumber: 1,
          pov: "林凡",
          goal: "继续承受深井压力",
          conflict: "危险任务逼近",
          turn: "林凡开始想躲开这条线",
          result: "人物状态看起来突然反向转折",
          newInformation: ["深井下方可能埋着更大的秘密"],
          emotionalShift: "绷紧 -> 退缩",
          sourceParagraphs: ["林凡忽然只想安稳活下去。"],
        },
      ],
      characterStates: [
        {
          name: "林凡",
          desire: "先保住命，不再继续追查",
          fear: "继续追查只会害死自己",
          misbelief: "真相根本不值得追",
          recentDecision: "先避开深井",
          decisionCost: "会错过继续追查旧线的机会",
          relationshipShift: ["与母亲旧线拉开距离"],
          arcProgress: "彻底转向退缩",
          presentInChapter: true,
        },
      ],
      themeReport: {
        chapterNumber: 4,
        activeThemes: [],
      },
      styleReport: {
        averageSentenceLength: 12,
        dialogueRatio: 0.05,
        descriptionRatio: 0.2,
        rhythmNote: "",
        adherenceNote: "",
        styleDriftPoints: [],
        dialogueHomogeneitySpots: [],
        descriptionBalanceNote: "",
      },
      readerReport: {
        chapterNumber: 4,
        scores: {
          hook: 6,
          momentum: 6,
          emotionalPeak: 6,
          suspense: 6,
          memorability: 6,
        },
        summary: "人物状态像是突然换了一套。", 
        strengths: [],
        risks: ["林凡的欲望、恐惧和误判都突然改口，但缺少中间桥接。"],
        revisionSuggestions: [],
      },
      gateDecision: {
        chapterNumber: 4,
        gate: null,
        required: false,
        rationale: "",
      },
      revisionBrief: "",
    },
    settlement: {
      chapterSummary: {
        chapterNumber: 4,
        title: "冷井口",
        summary: "林凡像是突然想放弃旧线。",
        keyEvents: ["林凡想避开深井与旧线"],
        changedCharacters: [],
        openedLoopIds: [],
        advancedLoopIds: [],
        closedLoopIds: [],
      },
      chapterStateDelta: {
        chapterNumber: 4,
        title: "冷井口",
        changedCharacters: [],
        chronologyInsertions: [
          {
            eventId: "ch0004-scene-1",
            chapterNumber: 4,
            sceneNumber: 1,
            sceneId: "scene-1",
            actors: ["林凡"],
            summary: "林凡想避开深井",
            consequence: "他不再主动追查旧线",
          },
        ],
        updatedLoops: [],
        stateHighlights: ["林凡状态突然反向转折"],
      },
      chronology: {
        events: [
          {
            eventId: "ch0004-scene-1",
            chapterNumber: 4,
            sceneNumber: 1,
            sceneId: "scene-1",
            actors: ["林凡"],
            summary: "林凡想避开深井",
            consequence: "他不再主动追查旧线",
          },
        ],
      },
      openLoops: {
        loops: [],
      },
    },
    previousChronology: {
      events: [],
    },
    previousOpenLoops: {
      loops: [],
    },
    previousCharacterHistory: [
      {
        name: "林凡",
        latestState: {
          name: "林凡",
          desire: "找出母亲失踪真相",
          fear: "真相会证明母亲不是失踪而是被人故意带走",
          misbelief: "只要追得够快就能撑住代价",
          recentDecision: "继续追查门铃声",
          decisionCost: "会更深卷进旧案",
          relationshipShift: ["与母亲留下的线索重新绑定"],
          arcProgress: "开始主动逼近真相线",
          presentInChapter: true,
        },
        timeline: [],
      },
    ],
    worldRules: {
      rules: [],
    },
  });

  assert.equal(report.blocking, true);
  assert.ok(report.issues.some((issue) => issue.code === "character_state_conflict"));
});

test("continuity agent flags duplicate or contradictory open loop updates", () => {
  const agent = new ContinuityAgent();
  const report = agent.audit({
    chapterNumber: 5,
    draft: {
      chapterNumber: 5,
      title: "旧仇新账",
      content: "赵执事的断供威胁仍然悬着，后续打压只会更狠，但 settlement 却一边把旧线关掉，一边又新开了一条几乎同义的威胁线。",
      summary: "工作稿",
      basedOnPlan: 5,
    },
    plan: {
      targetChapterNumber: 5,
      chapterMission: "让旧仇变成制度性围剿。",
      readerGoal: "承接旧威胁，不要重复开线。",
      sceneBlueprint: [
        {
          sceneId: "scene-1",
          sceneAnchor: "scene-1-旧仇",
          sceneNumber: 1,
          pov: "林凡",
          goal: "让赵执事的旧仇继续落地",
          conflict: "断供与危险差事一起压来",
          turn: "打压从私怨变成制度性围剿",
          result: "后续压力更重",
          newInformation: ["记录弟子也开始配合打压"],
          emotionalShift: "绷紧 -> 发冷",
          drivingCharacter: "赵执事",
          opposingForce: "林凡",
          decision: "先顶住这一轮围剿",
          cost: "资源和退路都继续被掐紧",
          relationshipChange: "旧仇彻底转成公开打压",
          thematicTension: "旧仇没有过去，只是换了更硬的壳",
          valuePositionA: "低头",
          valuePositionB: "硬抗",
          sceneStance: "继续压向更冷现实",
          styleDirective: "快节奏",
        },
      ],
      characterIntent: [],
      themeIntent: "代价继续升级",
      thematicQuestion: "旧威胁如何滚成更大的现实压力",
      styleProfile: {
        narrationStyle: "直接",
        dialogueStyle: "克制",
        pacingProfile: "快",
        descriptionDensity: "低",
        toneConstraints: [],
      },
      gateNote: "",
    },
    analysis: {
      scenes: [
        {
          sceneId: "scene-1",
          sceneAnchor: "scene-1-旧仇",
          sceneNumber: 1,
          pov: "林凡",
          goal: "让赵执事的旧仇继续落地",
          conflict: "断供与危险差事一起压来",
          turn: "打压从私怨变成制度性围剿",
          result: "后续压力更重",
          newInformation: ["记录弟子也开始配合打压"],
          emotionalShift: "绷紧 -> 发冷",
          sourceParagraphs: ["赵执事的断供威胁仍然悬着，后续打压只会更狠。"],
        },
      ],
      characterStates: [
        {
          name: "林凡",
          desire: "顶住围剿继续活下去",
          fear: "资源和退路都被掐断",
          misbelief: "只要咬住牙就还能单扛过去",
          recentDecision: "先顶住这一轮围剿",
          decisionCost: "资源和退路都继续被掐紧",
          relationshipShift: ["赵执事旧仇彻底转成公开打压"],
          arcProgress: "连续代价升级",
          presentInChapter: true,
        },
      ],
      themeReport: {
        chapterNumber: 5,
        activeThemes: [],
      },
      styleReport: {
        averageSentenceLength: 14,
        dialogueRatio: 0.1,
        descriptionRatio: 0.2,
        rhythmNote: "",
        adherenceNote: "",
        styleDriftPoints: [],
        dialogueHomogeneitySpots: [],
        descriptionBalanceNote: "",
      },
      readerReport: {
        chapterNumber: 5,
        scores: {
          hook: 7,
          momentum: 7,
          emotionalPeak: 7,
          suspense: 7,
          memorability: 7,
        },
        summary: "旧威胁还在，但账本处理方式很乱。",
        strengths: [],
        risks: ["旧线像是被重复开线又矛盾关闭。"],
        revisionSuggestions: [],
      },
      gateDecision: {
        chapterNumber: 5,
        gate: null,
        required: false,
        rationale: "",
      },
      revisionBrief: "",
    },
    settlement: {
      chapterSummary: {
        chapterNumber: 5,
        title: "旧仇新账",
        summary: "旧威胁继续存在，但账本把它处理成了互相冲突的两条线。",
        keyEvents: ["旧仇继续压上来"],
        changedCharacters: [],
        openedLoopIds: ["loop-ch0005-01"],
        advancedLoopIds: [],
        closedLoopIds: ["loop-ch0001-01"],
      },
      chapterStateDelta: {
        chapterNumber: 5,
        title: "旧仇新账",
        changedCharacters: [],
        chronologyInsertions: [
          {
            eventId: "ch0005-scene-1",
            chapterNumber: 5,
            sceneNumber: 1,
            sceneId: "scene-1",
            actors: ["林凡", "赵执事"],
            summary: "赵执事继续断供并加重围剿",
            consequence: "后续资源和危险差事都更紧",
          },
        ],
        updatedLoops: [
          {
            loopId: "loop-ch0001-01",
            action: "closed",
            description: "后续资源可能被彻底断供，甚至被安排危险差事",
            evidence: "scene-1",
          },
          {
            loopId: "loop-ch0005-01",
            action: "opened",
            description: "后续资源会继续被断供，危险差事也会更狠",
            evidence: "scene-1",
          },
        ],
        stateHighlights: ["旧威胁名义关闭、实际换名继续存在"],
      },
      chronology: {
        events: [
          {
            eventId: "ch0005-scene-1",
            chapterNumber: 5,
            sceneNumber: 1,
            sceneId: "scene-1",
            actors: ["林凡", "赵执事"],
            summary: "赵执事继续断供并加重围剿",
            consequence: "后续资源和危险差事都更紧",
          },
        ],
      },
      openLoops: {
        loops: [
          {
            loopId: "loop-ch0001-01",
            type: "threat",
            introducedInChapter: 1,
            owner: "赵执事",
            description: "后续资源可能被彻底断供，甚至被安排危险差事",
            expectedPayoffWindow: "soon",
            urgency: "high",
            status: "closed",
            payoffConstraints: ["近几章必须承接断供或危险差事"],
            relatedEntities: ["赵执事", "林凡"],
            evidenceRefs: ["scene-1"],
            lastUpdatedChapter: 5,
          },
          {
            loopId: "loop-ch0005-01",
            type: "threat",
            introducedInChapter: 5,
            owner: "赵执事",
            description: "后续资源会继续被断供，危险差事也会更狠",
            expectedPayoffWindow: "soon",
            urgency: "high",
            status: "open",
            payoffConstraints: ["下章继续承接打压"],
            relatedEntities: ["赵执事", "林凡"],
            evidenceRefs: ["scene-1"],
            lastUpdatedChapter: 5,
          },
        ],
      },
    },
    previousChronology: {
      events: [],
    },
    previousOpenLoops: {
      loops: [
        {
          loopId: "loop-ch0001-01",
          type: "threat",
          introducedInChapter: 1,
          owner: "赵执事",
          description: "后续资源可能被彻底断供，甚至被安排危险差事",
          expectedPayoffWindow: "soon",
          urgency: "high",
          status: "open",
          payoffConstraints: ["近几章必须承接断供或危险差事"],
          relatedEntities: ["赵执事", "林凡"],
          evidenceRefs: ["scene-4"],
          lastUpdatedChapter: 1,
        },
      ],
    },
    previousCharacterHistory: [],
    worldRules: {
      rules: [],
    },
  });

  assert.equal(report.blocking, true);
  assert.ok(report.issues.some((issue) => issue.code === "open_loop_conflict"));
});
