import test from "node:test";
import assert from "node:assert/strict";
import { SettlementAgent } from "../dist/core/modules/settlement-agent.js";

test("settlement agent produces summary, state delta, chronology, open loops, and theme progression", () => {
  const agent = new SettlementAgent();
  const result = agent.settle({
    chapterNumber: 1,
    draft: {
      chapterNumber: 1,
      title: "第一次反抗",
      content: "林凡当众夺回灵石。赵执事当场记恨，并放话后续要断供打压。",
      summary: "工作稿",
      basedOnPlan: 1,
    },
    plan: {
      targetChapterNumber: 1,
      chapterMission: "主角第一次反抗规则，并获得短期收益，同时埋下代价。",
      readerGoal: "让读者获得爽点与隐患感。",
      sceneBlueprint: [
        {
          sceneId: "scene-1",
          sceneAnchor: "scene-1-linfan",
          sceneNumber: 1,
          pov: "林凡",
          goal: "在资源分发中建立不公",
          conflict: "陈师兄与赵执事联手压人",
          turn: "林凡意识到继续忍只会失去最后一块灵石",
          result: "林凡当众夺回灵石，但被赵执事记恨",
          newInformation: ["赵执事会在后续资源上打压林凡"],
          emotionalShift: "压抑 -> 爆发",
          drivingCharacter: "林凡",
          opposingForce: "赵执事",
          decision: "当众反抗",
          cost: "后续资源被断供",
          relationshipChange: "林凡与赵执事彻底对立",
          thematicTension: "反抗有代价",
          valuePositionA: "反抗",
          valuePositionB: "忍耐",
          sceneStance: "偏向反抗",
          styleDirective: "快节奏",
        },
      ],
      characterIntent: [],
      themeIntent: "推进反抗有代价",
      thematicQuestion: "弱者想改变命运，是否注定要付代价？",
      styleProfile: {
        narrationStyle: "直接",
        dialogueStyle: "锋利",
        pacingProfile: "快",
        descriptionDensity: "低",
        toneConstraints: [],
      },
      gateNote: "",
    },
    analysis: {
      scenes: [
        {
          sceneId: "scene-1",
          sceneAnchor: "scene-1-linfan",
          sceneNumber: 1,
          pov: "林凡",
          goal: "在资源分发中建立不公",
          conflict: "陈师兄与赵执事联手压人",
          turn: "林凡意识到继续忍只会失去最后一块灵石",
          result: "林凡当众夺回灵石，但被赵执事记恨",
          newInformation: ["赵执事会在后续资源上打压林凡"],
          emotionalShift: "压抑 -> 爆发",
          sourceParagraphs: ["林凡当众夺回灵石。赵执事当场记恨，并放话后续要断供打压。"],
        },
      ],
      characterStates: [
        {
          name: "林凡",
          desire: "改变命运",
          fear: "继续被踩在底层",
          misbelief: "只要再忍一忍就能熬过去",
          recentDecision: "当众反抗陈师兄",
          decisionCost: "赵执事开始记恨并可能断供",
          relationshipShift: ["林凡与赵执事彻底结仇"],
          arcProgress: "第一次公开反抗规则",
          presentInChapter: true,
        },
      ],
      themeReport: {
        chapterNumber: 1,
        activeThemes: [],
      },
      styleReport: {
        averageSentenceLength: 18,
        dialogueRatio: 0.35,
        descriptionRatio: 0.15,
        rhythmNote: "",
        adherenceNote: "",
        styleDriftPoints: [],
        dialogueHomogeneitySpots: [],
        descriptionBalanceNote: "",
      },
      readerReport: {
        chapterNumber: 1,
        scores: {
          hook: 8,
          momentum: 8,
          emotionalPeak: 8,
          suspense: 7,
          memorability: 7,
        },
        summary: "爽点成立，但代价已经埋下。",
        strengths: [],
        risks: ["赵执事记恨林凡，后续资源可能被断供。"],
        revisionSuggestions: [],
      },
      gateDecision: {
        chapterNumber: 1,
        gate: null,
        required: false,
        rationale: "",
      },
      revisionBrief: "",
    },
    previousChronology: { events: [] },
    previousOpenLoops: { loops: [] },
    previousThemeProgression: { entries: [] },
  });

  assert.equal(result.chapterSummary.chapterNumber, 1);
  assert.equal(result.chapterStateDelta.chapterNumber, 1);
  assert.equal(result.chronology.events.length, 1);
  assert.ok(result.openLoops.loops.length >= 1);
  assert.equal(result.chapterStateDelta.sceneDeltas?.length, 1);
  assert.equal(result.themeProgression.entries.length, 1);
  assert.equal(result.chapterStateDelta.themeShift?.chapterNumber, 1);
  assert.ok(result.relationships.entries.some((entry) => entry.characters.includes("林凡")));
  assert.ok(result.chapterSummary.openedLoopIds.length >= 1);
  assert.ok(result.chapterStateDelta.updatedLoops.some((loop) => loop.action === "opened"));
  assert.match(result.chronology.events[0].summary, /反抗|夺回|灵石/u);
  assert.match(result.chronology.events[0].consequence, /断供|记恨|打压/u);
  assert.ok(result.openLoops.loops.some((loop) => /断供|记恨/u.test(loop.description)));
});

test("settlement agent prefers markerless prose paragraphs over noisy analysis excerpts", () => {
  const agent = new SettlementAgent();
  const result = agent.settle({
    chapterNumber: 2,
    draft: {
      chapterNumber: 2,
      title: "矿洞后的夜里",
      content: [
        "# 第2章 矿洞后的夜里",
        "",
        "林凡在矿洞里领到最脏最危险的一段废道清理任务，负责记录的弟子还故意少给他半袋照明石。",
        "",
        "他回到木屋时，发现门口挂着一张新的差役牌：明日起转去西三区深井，若拒不服从，停发三月配给。",
        "",
        "---",
        "基于规划章节: 2",
      ].join("\n"),
      summary: "工作稿",
      basedOnPlan: 2,
    },
    plan: {
      targetChapterNumber: 2,
      chapterMission: "把赵执事的打压转成具体苦役，并让林凡意识到自己已经没有退路。",
      readerGoal: "承接上一章代价，让压迫落地。",
      sceneBlueprint: [
        {
          sceneId: "scene-1",
          sceneAnchor: "scene-1-kuangdong",
          sceneNumber: 1,
          pov: "林凡",
          goal: "把打压变成具体苦役",
          conflict: "林凡被分到最危险的废道，还被克扣照明石",
          turn: "他确认赵执事已经开始动手卡资源",
          result: "林凡意识到打压不是口头威胁，而是马上生效",
          newInformation: ["外门记录弟子也开始配合赵执事压人"],
          emotionalShift: "烦闷 -> 警惕",
          drivingCharacter: "赵执事",
          opposingForce: "林凡的残余安全感",
          decision: "林凡决定先把苦役扛下来，再找机会回敬",
          cost: "他必须接受更危险的差役",
          relationshipChange: "林凡与赵执事的结怨转成持续打压",
          thematicTension: "反抗之后，代价持续追上来",
          valuePositionA: "低头换资源",
          valuePositionB: "硬扛打压找活路",
          sceneStance: "压向更冷的现实代价",
          styleDirective: "快节奏，不抒情。",
        },
        {
          sceneId: "scene-2",
          sceneAnchor: "scene-2-shenjing",
          sceneNumber: 2,
          pov: "林凡",
          goal: "把后续威胁钉成下一章必须承接的事项",
          conflict: "新的差役牌把林凡逼向更危险的深井",
          turn: "停发三月配给的处罚被直接写死",
          result: "林凡没有退路，只能准备去更危险的地方",
          newInformation: ["西三区深井会成为下一章直接压力点"],
          emotionalShift: "警惕 -> 更冷的决意",
          drivingCharacter: "赵执事",
          opposingForce: "林凡的生存余地",
          decision: "林凡决定接下这张差役牌",
          cost: "一旦拒绝就会失去三月配给",
          relationshipChange: "赵执事与林凡从报复转成制度性围剿",
          thematicTension: "代价不是一次性损失，而是持续升级",
          valuePositionA: "退让保命",
          valuePositionB: "硬扛到底",
          sceneStance: "把下一章钩子钉在危险任务上",
          styleDirective: "结尾留钩子。",
        },
      ],
      characterIntent: [],
      themeIntent: "推进反抗有代价",
      thematicQuestion: "第一次反抗之后，代价会如何持续升级？",
      styleProfile: {
        narrationStyle: "直接",
        dialogueStyle: "克制",
        pacingProfile: "快",
        descriptionDensity: "低",
        toneConstraints: [],
      },
      gateNote: "",
    },
    analysis: {
      scenes: [
        {
          sceneId: "scene-1",
          sceneAnchor: "scene-1-kuangdong",
          sceneNumber: 1,
          pov: "林凡",
          goal: "把打压变成具体苦役",
          conflict: "赵执事开始卡资源",
          turn: "林凡意识到威胁已经生效",
          result: "林凡被迫接受危险苦役",
          newInformation: ["赵执事已经动手"],
          emotionalShift: "烦闷 -> 警惕",
          sourceParagraphs: ["场景结束时获得有限推进，赵执事会公开偏帮有背景的弟子。"],
        },
        {
          sceneId: "scene-2",
          sceneAnchor: "scene-2-shenjing",
          sceneNumber: 2,
          pov: "林凡",
          goal: "把威胁钉成下一章压力点",
          conflict: "新的差役牌逼他去深井",
          turn: "停发三月配给被写死",
          result: "林凡没有退路",
          newInformation: ["深井任务是下一章主压力"],
          emotionalShift: "警惕 -> 决意",
          sourceParagraphs: ["真正推动这个场景的是价值站队。"],
        },
      ],
      characterStates: [
        {
          name: "林凡",
          desire: "活下去并向上爬",
          fear: "被断供后彻底失去修炼机会",
          misbelief: "只要忍住就能熬过去",
          recentDecision: "先接下差役牌，再找机会回敬",
          decisionCost: "拒绝会失去三月配给，接受则要进更危险的深井",
          relationshipShift: ["与赵执事的结怨升级为持续打压"],
          arcProgress: "开始适应反抗后的连续代价",
          presentInChapter: true,
        },
      ],
      themeReport: {
        chapterNumber: 2,
        activeThemes: [],
      },
      styleReport: {
        averageSentenceLength: 16,
        dialogueRatio: 0.05,
        descriptionRatio: 0.3,
        rhythmNote: "",
        adherenceNote: "",
        styleDriftPoints: [],
        dialogueHomogeneitySpots: [],
        descriptionBalanceNote: "",
      },
      readerReport: {
        chapterNumber: 2,
        scores: {
          hook: 7,
          momentum: 7,
          emotionalPeak: 6,
          suspense: 7,
          memorability: 6,
        },
        summary: "代价开始压实。",
        strengths: [],
        risks: ["西三区深井差役会在下一章成为直接威胁。"],
        revisionSuggestions: [],
      },
      gateDecision: {
        chapterNumber: 2,
        gate: null,
        required: false,
        rationale: "",
      },
      revisionBrief: "",
    },
    previousChronology: { events: [] },
    previousOpenLoops: { loops: [] },
    previousThemeProgression: { entries: [] },
  });

  assert.equal(result.chronology.events.length, 2);
  assert.ok(result.chronology.events.every((event) => !/场景结束时获得有限推进|真正推动这个场景/u.test(event.summary)));
  assert.ok(result.chronology.events.some((event) => /停发三月配给|深井/u.test(event.consequence) || /停发三月配给|深井/u.test(event.summary)));
  assert.ok(result.openLoops.loops.some((loop) => /深井|停发三月配给/u.test(loop.description)));
  assert.doesNotMatch(result.chapterSummary.summary, /场景结束时获得有限推进|真正推动这个场景/u);
});

test("settlement agent records reveal ledger entries when an old mystery is explicitly advanced", () => {
  const agent = new SettlementAgent();
  const result = agent.settle({
    chapterNumber: 3,
    draft: {
      chapterNumber: 3,
      title: "门铃声后的名字",
      content: "林凡终于明白，母亲失踪那夜的门铃声不是巧合。原来那串门铃声是有人故意留下的暗号。",
      summary: "工作稿",
      basedOnPlan: 3,
    },
    plan: {
      targetChapterNumber: 3,
      chapterMission: "把旧谜题往前推进一层。",
      readerGoal: "让读者感觉到真相开始露头。",
      sceneBlueprint: [
        {
          sceneId: "scene-1",
          sceneAnchor: "scene-1-doorbell",
          sceneNumber: 1,
          pov: "林凡",
          goal: "触碰母亲失踪之谜",
          conflict: "记忆与线索对不上",
          turn: "林凡终于听懂那串门铃声的意义",
          result: "旧谜题被明确推进",
          newInformation: ["门铃声是有人故意留下的暗号"],
          emotionalShift: "困惑 -> 发冷",
          drivingCharacter: "林凡",
          opposingForce: "旧记忆",
          decision: "继续追查门铃声",
          cost: "会更深卷进旧案",
          relationshipChange: "与母亲失踪线重新绑定",
          thematicTension: "真相越近代价越高",
          valuePositionA: "停下自保",
          valuePositionB: "继续追查",
          sceneStance: "压向真相",
          styleDirective: "压低说明，保留悬念。",
        },
      ],
      characterIntent: [],
      themeIntent: "真相的代价",
      thematicQuestion: "追查真相是否值得继续付代价？",
      styleProfile: {
        narrationStyle: "直接",
        dialogueStyle: "克制",
        pacingProfile: "快",
        descriptionDensity: "低",
        toneConstraints: [],
      },
      gateNote: "",
    },
    analysis: {
      scenes: [
        {
          sceneId: "scene-1",
          sceneAnchor: "scene-1-doorbell",
          sceneNumber: 1,
          pov: "林凡",
          goal: "触碰母亲失踪之谜",
          conflict: "记忆与线索对不上",
          turn: "林凡终于听懂那串门铃声的意义",
          result: "旧谜题被明确推进",
          newInformation: ["门铃声是有人故意留下的暗号"],
          emotionalShift: "困惑 -> 发冷",
          sourceParagraphs: ["林凡终于明白，母亲失踪那夜的门铃声不是巧合。"],
        },
      ],
      characterStates: [
        {
          name: "林凡",
          desire: "找出母亲失踪真相",
          fear: "真相会把自己拖进更深的危险",
          misbelief: "只要追得够快就能扛住代价",
          recentDecision: "继续追查门铃声",
          decisionCost: "会更深卷进旧案",
          relationshipShift: ["与母亲失踪线重新绑定"],
          arcProgress: "开始主动逼近真相线",
          presentInChapter: true,
        },
      ],
      themeReport: {
        chapterNumber: 3,
        activeThemes: [],
      },
      styleReport: {
        averageSentenceLength: 14,
        dialogueRatio: 0.05,
        descriptionRatio: 0.2,
        rhythmNote: "",
        adherenceNote: "",
        styleDriftPoints: [],
        dialogueHomogeneitySpots: [],
        descriptionBalanceNote: "",
      },
      readerReport: {
        chapterNumber: 3,
        scores: {
          hook: 8,
          momentum: 7,
          emotionalPeak: 7,
          suspense: 8,
          memorability: 7,
        },
        summary: "旧谜题明显往前推进了。",
        strengths: [],
        risks: ["真相线一旦被推进，后续必须继续承接。"],
        revisionSuggestions: [],
      },
      gateDecision: {
        chapterNumber: 3,
        gate: null,
        required: false,
        rationale: "",
      },
      revisionBrief: "",
    },
    previousChronology: { events: [] },
    previousOpenLoops: {
      loops: [
        {
          loopId: "loop-ch0001-02",
          type: "mystery",
          introducedInChapter: 1,
          owner: "林凡",
          description: "母亲失踪那夜的门铃声到底意味着什么？",
          expectedPayoffWindow: "soon",
          urgency: "high",
          status: "open",
          payoffConstraints: ["近几章必须持续推进谜题"],
          relatedEntities: ["林凡", "母亲", "门铃声"],
          evidenceRefs: ["scene-4"],
          lastUpdatedChapter: 1,
        },
      ],
    },
    previousThemeProgression: { entries: [] },
  });

  assert.equal(result.reveals.entries.length, 1);
  assert.equal(result.reveals.entries[0].sourceLoopId, "loop-ch0001-02");
  assert.match(result.reveals.entries[0].revealedTruth, /门铃声|暗号|真相/u);
});

test("settlement agent reuses unchanged scene deltas and appends theme progression on incremental re-settlement", () => {
  const agent = new SettlementAgent();
  const result = agent.settle({
    chapterNumber: 2,
    draft: {
      chapterNumber: 2,
      title: "第二次断供",
      content: [
        "林凡在矿洞里咬牙把苦役扛了下来。",
        "",
        "天黑后，他见到赤膊记录弟子把停发三月配给的牌子挂到他门前。",
      ].join("\n"),
      summary: "工作稿",
      basedOnPlan: 2,
    },
    plan: {
      targetChapterNumber: 2,
      chapterMission: "把反抗后的代价继续压实。",
      readerGoal: "让读者感到后果已经生效。",
      sceneBlueprint: [
        {
          sceneId: "scene-1",
          sceneAnchor: "scene-1-mine",
          sceneNumber: 1,
          pov: "林凡",
          goal: "接管苦役",
          conflict: "林凡被迫扛下最危险的废道清理",
          turn: "他意识到惩罚已经开始生效",
          result: "林凡先把苦役接了下来",
          newInformation: ["赵执事开始把打压变成日常"],
          emotionalShift: "愤怒 -> 隐忍",
          drivingCharacter: "林凡",
          opposingForce: "赵执事",
          decision: "先接下苦役",
          cost: "必须去更危险的废道",
          relationshipChange: "与赵执事的对立变成持续打压",
          thematicTension: "反抗之后，代价开始生效",
          valuePositionA: "再忍一步",
          valuePositionB: "硬扛到底",
          sceneStance: "压向代价",
          styleDirective: "快节奏",
        },
        {
          sceneId: "scene-2",
          sceneAnchor: "scene-2-order",
          sceneNumber: 2,
          pov: "林凡",
          goal: "把威胁写死",
          conflict: "停发三月配给的处罚被直接挂到门前",
          turn: "林凡确认自己已经没有退路",
          result: "深井差役成为下一章的压力入口",
          newInformation: ["西三区深井会是下一章的直接危险"],
          emotionalShift: "隐忍 -> 决意",
          drivingCharacter: "赵执事",
          opposingForce: "林凡",
          decision: "接下差役牌",
          cost: "一旦拒绝就会失去三月配给",
          relationshipChange: "赵执事把打压变成制度性围剿",
          thematicTension: "代价不是一次性的，而是持续升级",
          valuePositionA: "低头保命",
          valuePositionB: "硬扛找活路",
          sceneStance: "压向更冷的现实",
          styleDirective: "结尾留钩子",
        },
      ],
      characterIntent: [],
      themeIntent: "反抗有代价",
      thematicQuestion: "反抗后的代价会如何持续升级？",
      styleProfile: {
        narrationStyle: "直接",
        dialogueStyle: "克制",
        pacingProfile: "快",
        descriptionDensity: "低",
        toneConstraints: [],
      },
      gateNote: "",
    },
    analysis: {
      scenes: [
        {
          sceneId: "scene-1",
          sceneAnchor: "scene-1-mine",
          sceneNumber: 1,
          pov: "林凡",
          goal: "接管苦役",
          conflict: "林凡被迫扛下最危险的废道清理",
          turn: "他意识到惩罚已经开始生效",
          result: "林凡先把苦役接了下来",
          newInformation: ["赵执事开始把打压变成日常"],
          emotionalShift: "愤怒 -> 隐忍",
          sourceParagraphs: ["林凡在矿洞里咬牙把苦役扛了下来。"],
        },
        {
          sceneId: "scene-2",
          sceneAnchor: "scene-2-order",
          sceneNumber: 2,
          pov: "林凡",
          goal: "把威胁写死",
          conflict: "停发三月配给的处罚被直接挂到门前",
          turn: "林凡确认自己已经没有退路",
          result: "深井差役成为下一章的压力入口",
          newInformation: ["西三区深井会是下一章的直接危险"],
          emotionalShift: "隐忍 -> 决意",
          sourceParagraphs: ["天黑后，他见到赤膊记录弟子把停发三月配给的牌子挂到他门前。"],
        },
      ],
      characterStates: [
        {
          name: "林凡",
          desire: "活下去并向上爬",
          fear: "失去配给后再也没有修炼机会",
          misbelief: "再忍一步就能再换一口气",
          recentDecision: "接下差役牌",
          decisionCost: "一旦拒绝就会失去三月配给",
          relationshipShift: ["与赵执事的对立变成持续打压"],
          arcProgress: "开始适应反抗后的持续代价",
          presentInChapter: true,
        },
      ],
      themeReport: {
        chapterNumber: 2,
        activeThemes: [
          {
            theme: "反抗有代价",
            antiTheme: "低头就能换安全",
            valueConflict: "生存 vs 尊严",
            themeSignalCount: 3,
            antiSignalCount: 1,
            interpretation: "林凡开始意识到反抗后的代价会持续升级。",
          },
        ],
      },
      styleReport: {
        averageSentenceLength: 16,
        dialogueRatio: 0.05,
        descriptionRatio: 0.2,
        rhythmNote: "",
        adherenceNote: "",
        styleDriftPoints: [],
        dialogueHomogeneitySpots: [],
        descriptionBalanceNote: "",
      },
      readerReport: {
        chapterNumber: 2,
        scores: {
          hook: 7,
          momentum: 7,
          emotionalPeak: 6,
          suspense: 7,
          memorability: 6,
        },
        summary: "代价开始压实。",
        strengths: [],
        risks: ["停发三月配给会把林凡逼向更危险的深井。"],
        revisionSuggestions: [],
      },
      gateDecision: {
        chapterNumber: 2,
        gate: null,
        required: false,
        rationale: "",
      },
      revisionBrief: "",
    },
    previousChronology: {
      events: [
        {
          eventId: "ch0001-scene-1",
          chapterNumber: 1,
          sceneNumber: 1,
          sceneId: "scene-1",
          actors: ["林凡", "赵执事"],
          summary: "林凡当众夺回灵石",
          consequence: "赵执事记恨，后续资源将被打压",
        },
      ],
    },
    previousOpenLoops: {
      loops: [
        {
          loopId: "loop-ch0001-01",
          type: "threat",
          introducedInChapter: 1,
          owner: "赵执事",
          description: "赵执事会报复林凡，资源可能被断供",
          expectedPayoffWindow: "soon",
          urgency: "high",
          status: "open",
          payoffConstraints: [],
          relatedEntities: ["林凡", "赵执事"],
          evidenceRefs: ["scene-1"],
          lastUpdatedChapter: 1,
        },
      ],
    },
    previousThemeProgression: {
      entries: [
        {
          chapterNumber: 1,
          primaryTheme: "反抗有代价",
          antiTheme: "低头就能换安全",
          thematicQuestion: "第一次反抗之后，代价会不会继续升级？",
          movementSummary: "第一次公开反抗换来了早期胜利，但也埋下了后续打压。",
          stance: "toward_theme",
          pressurePoint: "短期胜利之后，制度性代价必须都落地",
          carrierCharacters: ["林凡", "赵执事"],
          supportingSceneNumbers: [3, 4],
          evidenceRefs: ["scene-3", "scene-4"],
        },
      ],
    },
    previousChapterStateDelta: {
      chapterNumber: 2,
      title: "第二次断供",
      changedCharacters: [],
      sceneDeltas: [
        {
          sceneNumber: 1,
          sceneId: "scene-1",
          sceneAnchor: "scene-1-mine",
          actors: ["林凡", "赵执事"],
          summary: "旧版 scene 1 summary",
          consequence: "旧版 scene 1 consequence",
          stateHighlights: ["old-scene-1"],
          loopIds: ["loop-ch0001-01"],
          revealIds: [],
          relationshipIds: [],
          themeBeat: "旧版 theme beat",
        },
        {
          sceneNumber: 2,
          sceneId: "scene-2",
          sceneAnchor: "scene-2-order",
          actors: ["林凡"],
          summary: "旧版 scene 2 summary",
          consequence: "旧版 scene 2 consequence",
          stateHighlights: ["old-scene-2"],
          loopIds: [],
          revealIds: [],
          relationshipIds: [],
          themeBeat: "旧版 theme beat 2",
        },
      ],
      chronologyInsertions: [],
      updatedLoops: [],
      themeShift: {
        chapterNumber: 2,
        primaryTheme: "旧版主题",
        antiTheme: "旧版反主题",
        thematicQuestion: "旧版主题问题",
        movementSummary: "旧版主题推进",
        stance: "mixed",
        pressurePoint: "旧版主题压力",
        carrierCharacters: ["林凡"],
        supportingSceneNumbers: [1, 2],
        evidenceRefs: ["scene-1", "scene-2"],
      },
      stateHighlights: [],
    },
    rewrittenSceneNumbers: [2],
  });

  assert.equal(result.chapterStateDelta.sceneDeltas?.length, 2);
  assert.equal(result.chapterStateDelta.sceneDeltas?.[0].summary, "旧版 scene 1 summary");
  assert.notEqual(result.chapterStateDelta.sceneDeltas?.[1].summary, "旧版 scene 2 summary");
  assert.equal(result.themeProgression.entries.length, 2);
  assert.equal(result.themeProgression.entries[1].chapterNumber, 2);
  assert.equal(result.chapterStateDelta.themeShift?.chapterNumber, 2);
});
